mklink /j "C:\Games\World of Warcraft\_retail_\Interface" "%UserProfile%\Documents\My Games\WOW\Interface"
mklink /j "C:\Games\World of Warcraft\_retail_\WTF" "%UserProfile%\Documents\My Games\WOW\WTF"
mklink /J %UserProfile%\.ssh "%UserProfile%\Documents\Appdata\.ssh"
mklink /J %UserProfile%\.android "%UserProfile%\Documents\Appdata\.android"
mklink /J %UserProfile%\.vscode "%UserProfile%\Documents\Appdata\.vscode"
mklink /H %UserProfile%\.gitconfig "%UserProfile%\Documents\Appdata\.gitconfig"
